### ISSUE TITLE
Memory leaks and client pooling.

### ISSUE THREAD

**Issue by bmershon** [vitaly-t/pg-core#1]
### My Problem

My question relates to my use of the original pg library (and hopefully my future use of the pg-promise library). In my use case, a POST route provides a JSON object describing a Wikipedia article to a *search pipeline*; this object is used to search for relevant [blocks](http://bl.ocks.org) in response to a request sent from a chrome extension I've written.

*Here's a screenshot of an early prototype displaying results for a Wikipedia article.*

![l_system](https://cloud.githubusercontent.com/assets/3190945/11169766/d55c090a-8b8e-11e5-91ce-c436021192e2.png)

A search request for a page like the one you see above typically involves around 10 to 50 queries (reads) from the database. These queries currently must share one client, so they are satisifed one after the other until the that pg Client object's internal queryQueue is empty. Soon I hope to allow the search process for a single request to have it's own pool of clients to use for the completion of a search.

Here's the relevant code surrounding my call to my rudimentary search engine:

*routes/search.js*
```js
var express = require('express');
var router = express.Router();

var handler = require('../handlers/search-handler.js');

/* POST search object */
router.post('/', function (req, res) {
	var page = req.body;

	if(!page.title || !page.see_also || !page.categories) {
    	return res.sendStatus(400);
    	return;
	}
	// pass response to the middleware responsible for handling page
	handler.handlePage(page, res);
});

module.exports = router;
```

*handlers/search-handler.js*
```js
#!/usr/bin/env node

/*
	Copyright 2015
	Brooks Mershon, Manoj Kanagaraj, and Davis Treybig
*/

var pg = require("pg"),
	config = require('../config.json'),
	SearchEngines = require('../lib/search/SearchEngines.js');

/*
	Creates a new client and new SearchEngine.

	Sends response with error status 500 or JSON results.
*/
function handlePage(page, response){

	// new client for this request
	var client = new pg.Client(config);

	// new pg client with an internal queue of queries to execute
	client.connect(function(err) {
		if(err) {
			console.log(err);
			response.sendStatus(503);
			return;
		}
	});

	// create a new SearchEngine object with the current client connected to the database
	var SearchEngine = new SearchEngines.IterativeSearchEngine(client);

	var t0 = Date.now();

	try {
		SearchEngine.getPageResults(page, function(error, gists) {

			client.end();

			if(error) {
				console.log("search error", error);
				response.sendStatus(500);
				return;
			}

			var results = {};
			results.gists = gists;
			results.start = t0;
			results.end = Date.now();
			response.json(JSON.stringify(results, null, 2));
		});

	} catch(e) {
		response.sendStatus(500);
	}
};

module.exports = {
	handlePage: handlePage
};
```

First of all, I temporarily did away with the client pooling that pg provides because the pooling didn't seem to behave as I expected. For now, load testing works fine with my Amazon RDS up to around 250 (max_connections is 256) open connections to a PSQL database. When this limit is exceeded, connection errors come back (too many open connections) and I send a 503 response back to my Chrome Extension. Ideally, some reasonable client pooling should be done by my Express.js server. For now, I get a new client and manually call `end()` to disconnect it.

I'm currently using PM2 to keep the node script running.

During testing, I've noticed cpu usage and memory usage slowly increase as [PM2](https://github.com/Unitech/pm2) `pm2 monit` shows.

### My Question
I was hoping you might share your thoughts on memory usage, client pooling, and perhaps general strategies for making the best use of your **pg-promise** library and perhaps the new **pg-core** library.

Your insights and help would be greatly appreciated!

**Comment by vitaly-t** [comment]
One of the main strengths of pg-promise is guaranteed correct release of connections back to the pool. In a large application it is very easy to make a mistake and leak a connection in some places.

You would have to start using pg-promise to see if there is any issue with the number of connections.

Also, pg-promises exposes the `pg` module, so one can do `pgp.pg.defaults.poolSize = 123` in case the default is insufficient.

As far as pg-core goes, right now it is pretty much 1-to-1 with the original, minus some redundant code thrown away as well as support for native bindings. So, functionally, there should be no difference right now between using pg-promise 3.0 and 2.3.1.

In the future though, there is a possibility to improve pg-core as far as the connection pool goes. In fact, it is already better, since it is using the latest version of every package, including the pool library, as opposed to node-postgres that's full of very old package references.

Anyhow, pg-core is a very recent enterprise, which needs a good few tests added to it before considering making a change in the code.

**Comment by bmershon** [comment]
Thanks for the reply; I'll begin using pg-promise. I sure wish I'd found it earlier!

It turns out there were no memory leaks coming from the pg library itself.

**I am a little confused about how I might use your [detached and shared connections](https://github.com/vitaly-t/pg-promise#connections) to satisfy the following use case:**

There are a maximum number of connections that my database can handle. Call this number **M**.

A typical request results in a search which needs to make between 5 and 40 queries to the database. Let's say this is 40 queries in the worst case.  Call this number **Q**.

I'd like to maintain a concurrency level **R**, which is the number of current in-progress searches that I can perform.

100 in-progress searches (requests) could use up **R** x **Q** = 100 x 40 = 400 < **M** connections to the database.

This is in contrast to my current search pipeline which uses a single connection for all queries related to a search. In this *slower* case, *100* requests produces *100* connections to the database. I call this the "one-tier" client pooling method.

It seems like there needs to be a pool (or queue like Mike Bostock's queue-async) which manages the number of concurrent requests, and each request should itself have a small pool of clients to use up for the 40 or so queries that a typical search might execute in parallel.

I was hoping you might weigh in on this **two-tier** approach to pooling. Again, the second tier is an effort to allow an in-progress search to send its queries in parallel, rather than waiting for 40 or so queries to go one-at-a-time through a single connection. In a sense, the size of the first "pool" is **R**, and the size of each pool allocated to an in-progress search is **Q**.

Of course, the limit **M** inherent to the database must be respected at all times:

**R** x **Q** < **M**

Your thoughts would be greatly appreciated!

**Comment by vitaly-t** [comment]
You seem to be talking about a serious system, given how much thought you are putting into it :)

So here's my best advise on getting started.

* Wrap those 5-40 queries into a [tasks](https://github.com/vitaly-t/pg-promise#tasks).
* If the task makes changes to the database, execute as a transaction: `db.tx`
* If the task does only read-only operations, execute it as a task: `db.task`.

For easy analysis and understanding how everything works:

* Tag all of your tasks and transactions (name them): `db.task("myTask", cb)`, `db.tx("myTX", cb)`
* Use [pg-monitor](https://github.com/vitaly-t/pg-monitor) to see how everything is executing against the database. Here's [complete example](https://github.com/vitaly-t/pg-promise/blob/master/examples/monitor.js).

Once you get there, it will be easier to see how to proceed ;)

**Comment by bmershon** [comment]
This is very helpful.

I'm only a couple months or so into the project, but here's some background if you'd like to see how you library will get used "in the wild." Serious or not, this project is about an "experience," and a relational database is a first attempt to get this off the ground.

*Why start with a relational database?* Because this project started in a university course designed around relational algebra and XML and other "traditional" material. More advanced db systems that are better suited for information retrieval would make sense, but you have to start somewhere.

**Search:**: https://github.com/bmershon/wikiblocks-search

To quickly understand the spirit of the project, here's the extension with screenshots:

**Chrome extension:** https://github.com/wikiblocks/wikiblocks-chrome

Interestingly, with the restricted domain of STEM concepts, relational databases might not be such a bad place to start for my current model of information retrieval. Short, nominative strings like "Vector Space" and "Quicksort" and "Simplicial Complex" and "Spline Curve" lend themselves the type of associations I'm developing:

**gist to a tag**
**gist to a category**
**tag to a category**

My ultimate goal would be do go as far as relational database models can take me and then use that learning experience to inform a migration to a model that is better suited to the type of information retrieval I'm performing.

Any thoughts you have with regards to the project, or the use of your library are welcome. I know it's a lot to take in, but I wanted you to have some background in order to better understand my library-specific questions.

**Comment by vitaly-t** [comment]
I wouldn't speculate on which type of the database is best suited for your project, as it takes a good consideration to draw such a conclusion. But it may easily be that a non-relational system will be a better platform for you, like Mango DB.

Here's I can only advise on better use of this library, and I will leave it at that.

**Comment by bmershon** [comment]
Friendly follow-up:

I got started with transactions and it's smooth sailing:

https://github.com/bmershon/wikiblocks-data/blob/master/test/transaction-test.js

Your libraries/docs are a pleasure to use. I did have to comment out a single line in the *print* functions for pg-monitor to keep it from tripping up TAP-summarizers (e.g. faucet). Couldn't find a configuration to do so.

Thanks again for pointing me toward better tools.

Cheers!

**Comment by vitaly-t** [comment]
Which function did you have to comment out in pg-monitor? Was there an issue somewhere?

Some suggestions on your code...

When you call:
```js
        var queryString = "INSERT INTO Gist(gistid, username, description) VALUES($1, $2, $3)";
        var values = [gists[2].gistid, gists[2].username, gists[2].description.trim()];
```
In your gist type you can have a function that returns a trimmed version of description, like this:
```js
this.desc = function(){
   return this.description.trim();
};
```
in which case you can use it directly, and thus your code would be more elegant:
```js
        var queryString = "INSERT INTO Gist(gistid, username, description) VALUES(${gistid}, ${username}, ${desc})";
        var values = gists[2];
```

About the following:
```js
db.manyOrNone(queries.matchTag, ['color'])
```
just so, method manyOrNone has alias `any` ;)

About this line:
```js
pgp.end(); //close connections and exit
```
it terminates the library, either to be called when exiting the application, or never at all. In a real application you would never call it, and they are normally terminated by killing the process.

If you have issues regarding use of pg-promise or pg-monitor, please open an issue in the corresponding projects. In the meantime, I'm closing this one.

Good luck!

**Comment by bmershon** [comment]
@vitaly-t I'm using extend with success :+1:
