### ISSUE TITLE
Refcursor support for Node.js

### ISSUE THREAD

**Issue by nguruyeshwanth** [vitaly-t/pg-core#2]
Hello,

I am trying to call a stored proc from node which returns a refcursor, ideally I would like to FETCH ALL from the refcursor and utilize that result set for my front end dashboard data population.

Please let me know if this feature is supported and/or if there are any other packages that offer this functionality.

Regards,
Guru

**Comment by vitaly-t** [comment]
You should ask this question on [node-postgres](https://github.com/brianc/node-postgres) ;)

I can't answer it here. Also, at present I only support [pg-promise](https://github.com/vitaly-t/pg-promise) for PostgreSQL ;)
